# Generated by Django 5.1.2 on 2025-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasVerse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
