# Generated by Django 5.1.2 on 2025-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasVerse', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
